/* MiniJavaParser.java */
/* Generated By:JavaCC: Do not edit this line. MiniJavaParser.java */
  package Parse;
  import java.util.LinkedList;
  public class MiniJavaParser implements MiniJavaParserConstants {

/*********************/
/* MiniJava Grammar */
/*********************/

// Goal         ::=     MainClass ( ClassDeclaration | ThreadDeclaration )* <EOF>
  static final public Absyn.Program Goal() throws ParseException {LinkedList<Absyn.ClassDecl> classes = new LinkedList<Absyn.ClassDecl>();
    MainClassDeclaration(classes);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 6:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      if (jj_2_1(2147483647)) {
        ThreadDeclaration(classes);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 6:{
          ClassDeclaration(classes);
          break;
          }
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    jj_consume_token(0);
{if ("" != null) return new Absyn.Program(classes);}
    throw new Error("Missing return statement in function");
}

// MainClass    ::=     "class" Identifier "{" "public" "static" "void" "main"
//                     "(" "String" "[" "]" Identifier ")" "{"
//                     VarDeclaration* Statement* "}" "}"
  static final public Absyn.ClassDecl MainClassDeclaration(LinkedList<Absyn.ClassDecl> classes) throws ParseException {Token name, arg;
    LinkedList<Absyn.Formal> params = new LinkedList<Absyn.Formal>();
    LinkedList<Absyn.VarDecl> locals;
    LinkedList<Absyn.Stmt> stmts;
    LinkedList<Absyn.MethodDecl> methods = new LinkedList<Absyn.MethodDecl>();
    Absyn.ClassDecl cd;
    jj_consume_token(6);
    name = jj_consume_token(ID);
    jj_consume_token(36);
    jj_consume_token(7);
    jj_consume_token(8);
    jj_consume_token(12);
    jj_consume_token(44);
    jj_consume_token(38);
    jj_consume_token(45);
    jj_consume_token(40);
    jj_consume_token(41);
    arg = jj_consume_token(ID);
    jj_consume_token(39);
params.add(new Absyn.Formal(
                new Absyn.ArrayType(new Absyn.IdentifierType("String")),
                arg.toString()));
    jj_consume_token(36);
    locals = VarDeclarations();
    stmts = Statements();
    jj_consume_token(37);
    jj_consume_token(37);
methods.add(new Absyn.MethodDecl(
                null, false, "main", params, locals, stmts,
                new Absyn.IntegerLiteral(0)));

        cd = new Absyn.ClassDecl(
                name.toString(), null,
                new LinkedList<Absyn.VarDecl>(), methods);

        classes.add(cd);
        {if ("" != null) return cd;}
    throw new Error("Missing return statement in function");
}

// ClassDeclaration     ::=     "class" Identifier ( "extends" Identifier )?
//                              "{" ( FieldDeclaration | MethodDeclaration )* "}"
  static final public Absyn.ClassDecl ClassDeclaration(LinkedList<Absyn.ClassDecl> classes) throws ParseException {Token name, parentToken;
    String parent = null;
    Absyn.VarDecl field;
    Absyn.MethodDecl method;
    LinkedList<Absyn.VarDecl> fields = new LinkedList<Absyn.VarDecl>();
    LinkedList<Absyn.MethodDecl> methods = new LinkedList<Absyn.MethodDecl>();
    Absyn.ClassDecl cd;
    jj_consume_token(6);
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 9:{
      jj_consume_token(9);
      parentToken = jj_consume_token(ID);
parent = parentToken.toString();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(36);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 7:
      case 13:
      case 14:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      if (jj_2_2(2147483647)) {
        method = MethodDeclaration();
methods.add(method);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 13:
        case 14:
        case ID:{
          field = FieldDeclaration();
fields.add(field);
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    jj_consume_token(37);
cd = new Absyn.ClassDecl(name.toString(), parent, fields, methods);
        classes.add(cd);
        {if ("" != null) return cd;}
    throw new Error("Missing return statement in function");
}

// ThreadDeclaration    ::=     "class" Identifier "extends" "Thread"
//                              "{" ( FieldDeclaration | MethodDeclaration
//                              | VoidDeclaration )* "}"
  static final public Absyn.ThreadDecl ThreadDeclaration(LinkedList<Absyn.ClassDecl> classes) throws ParseException {Token name;
    Absyn.VarDecl field;
    Absyn.MethodDecl method;
    LinkedList<Absyn.VarDecl> fields = new LinkedList<Absyn.VarDecl>();
    LinkedList<Absyn.MethodDecl> methods = new LinkedList<Absyn.MethodDecl>();
    Absyn.ThreadDecl td;
    jj_consume_token(6);
    name = jj_consume_token(ID);
    jj_consume_token(9);
    jj_consume_token(46);
    jj_consume_token(36);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 7:
      case 13:
      case 14:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_3;
      }
      if (jj_2_3(2147483647)) {
        method = VoidDeclaration();
methods.add(method);
      } else if (jj_2_4(2147483647)) {
        method = MethodDeclaration();
methods.add(method);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 13:
        case 14:
        case ID:{
          field = FieldDeclaration();
fields.add(field);
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    jj_consume_token(37);
td = new Absyn.ThreadDecl(name.toString(), fields, methods);
        classes.add(td);
        {if ("" != null) return td;}
    throw new Error("Missing return statement in function");
}

// FieldDeclaration     ::=     Type Identifier ";"
  static final public Absyn.VarDecl FieldDeclaration() throws ParseException {Absyn.Type type;
    Token name;
    type = Type();
    name = jj_consume_token(ID);
    jj_consume_token(42);
{if ("" != null) return new Absyn.VarDecl(type, name.toString(), null);}
    throw new Error("Missing return statement in function");
}

// MethodDeclaration    ::=     "public" ( "synchronized" )? Type Identifier
//                              "(" Formals ")" "{"
//                              VarDeclaration* Statement*
//                              "return" Expression ";" "}"
  static final public Absyn.MethodDecl MethodDeclaration() throws ParseException {boolean synced = false;
    Absyn.Type returnType;
    Token name;
    LinkedList<Absyn.Formal> params;
    LinkedList<Absyn.VarDecl> locals;
    LinkedList<Absyn.Stmt> stmts;
    Absyn.Expr returnVal;
    jj_consume_token(7);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 11:{
      jj_consume_token(11);
synced = true;
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    returnType = Type();
    name = jj_consume_token(ID);
    jj_consume_token(38);
    params = Formals();
    jj_consume_token(39);
    jj_consume_token(36);
    locals = VarDeclarations();
    stmts = Statements();
    jj_consume_token(10);
    returnVal = Expression();
    jj_consume_token(42);
    jj_consume_token(37);
{if ("" != null) return new Absyn.MethodDecl(
                returnType, synced, name.toString(),
                params, locals, stmts, returnVal);}
    throw new Error("Missing return statement in function");
}

// VoidDeclaration      ::=     "public" "void" Identifier "(" ")"
//                              "{" VarDeclaration* Statement* "}"
  static final public Absyn.VoidDecl VoidDeclaration() throws ParseException {Token name;
    LinkedList<Absyn.VarDecl> locals;
    LinkedList<Absyn.Stmt> stmts;
    jj_consume_token(7);
    jj_consume_token(12);
    name = jj_consume_token(ID);
    jj_consume_token(38);
    jj_consume_token(39);
    jj_consume_token(36);
    locals = VarDeclarations();
    stmts = Statements();
    jj_consume_token(37);
{if ("" != null) return new Absyn.VoidDecl(name.toString(), locals, stmts);}
    throw new Error("Missing return statement in function");
}

// Formals              ::=     ( Type Identifier ( "," Type Identifier )* )?
  static final public LinkedList<Absyn.Formal> Formals() throws ParseException {Absyn.Type type;
    Token name;
    LinkedList<Absyn.Formal> params = new LinkedList<Absyn.Formal>();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 13:
    case 14:
    case ID:{
      type = Type();
      name = jj_consume_token(ID);
params.add(new Absyn.Formal(type, name.toString()));
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 43:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_4;
        }
        jj_consume_token(43);
        type = Type();
        name = jj_consume_token(ID);
params.add(new Absyn.Formal(type, name.toString()));
      }
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
{if ("" != null) return params;}
    throw new Error("Missing return statement in function");
}

// VarDeclarations      ::=     VarDeclaration*
  static final public LinkedList<Absyn.VarDecl> VarDeclarations() throws ParseException {Absyn.VarDecl var;
    LinkedList<Absyn.VarDecl> vars = new LinkedList<Absyn.VarDecl>();
    label_5:
    while (true) {
      if (jj_2_5(2147483647)) {
        ;
      } else {
        break label_5;
      }
      var = VarDeclaration();
vars.add(var);
    }
{if ("" != null) return vars;}
    throw new Error("Missing return statement in function");
}

// Statements           ::=     Statement*
  static final public LinkedList<Absyn.Stmt> Statements() throws ParseException {Absyn.Stmt stmt;
    LinkedList<Absyn.Stmt> stmts = new LinkedList<Absyn.Stmt>();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 15:
      case 17:
      case 20:
      case 36:
      case 47:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_6;
      }
      stmt = Statement();
stmts.add(stmt);
    }
{if ("" != null) return stmts;}
    throw new Error("Missing return statement in function");
}

// VarDeclaration       ::=     Type Identifier ( "=" Expression )? ";"
  static final public Absyn.VarDecl VarDeclaration() throws ParseException {Absyn.Type type;
    Token name;
    Absyn.Expr init = null;
    type = Type();
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 27:{
      jj_consume_token(27);
      init = Expression();
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(42);
{if ("" != null) return new Absyn.VarDecl(type, name.toString(), init);}
    throw new Error("Missing return statement in function");
}

// Type                 ::=     BaseType ( "[" "]" )*
  static final public Absyn.Type Type() throws ParseException {Absyn.Type type;
    type = BaseType();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 40:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_7;
      }
      jj_consume_token(40);
      jj_consume_token(41);
type = new Absyn.ArrayType(type);
    }
{if ("" != null) return type;}
    throw new Error("Missing return statement in function");
}

// BaseType             ::=     "int" | "boolean" | Identifier
  static final public Absyn.Type BaseType() throws ParseException {Token name;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 13:{
      jj_consume_token(13);
{if ("" != null) return new Absyn.IntegerType();}
      break;
      }
    case 14:{
      jj_consume_token(14);
{if ("" != null) return new Absyn.BooleanType();}
      break;
      }
    case ID:{
      name = jj_consume_token(ID);
{if ("" != null) return new Absyn.IdentifierType(name.toString());}
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// Statement            ::=     BlockStatement
//                         |    IfStatement
//                         |    WhileStatement
//                         |    AssignStatement
//                         |    XinuCallStatement
  static final public Absyn.Stmt Statement() throws ParseException {Absyn.Stmt stmt;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 36:{
      stmt = BlockStatement();
{if ("" != null) return stmt;}
      break;
      }
    case 15:{
      stmt = IfStatement();
{if ("" != null) return stmt;}
      break;
      }
    case 17:{
      stmt = WhileStatement();
{if ("" != null) return stmt;}
      break;
      }
    case 20:
    case ID:{
      stmt = AssignStatement();
{if ("" != null) return stmt;}
      break;
      }
    case 47:{
      stmt = XinuCallStatement();
{if ("" != null) return stmt;}
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// BlockStatement       ::=     "{" Statement* "}"
  static final public Absyn.BlockStmt BlockStatement() throws ParseException {LinkedList<Absyn.Stmt> stmts;
    jj_consume_token(36);
    stmts = Statements();
    jj_consume_token(37);
{if ("" != null) return new Absyn.BlockStmt(stmts);}
    throw new Error("Missing return statement in function");
}

// IfStatement          ::=     "if" "(" Expression ")" Statement
//                              ( "else" Statement )?
  static final public Absyn.IfStmt IfStatement() throws ParseException {Absyn.Expr test;
    Absyn.Stmt thenStmt;
    Absyn.Stmt elseStmt = null;
    jj_consume_token(15);
    jj_consume_token(38);
    test = Expression();
    jj_consume_token(39);
    thenStmt = Statement();
    if (jj_2_6(2)) {
      jj_consume_token(16);
      elseStmt = Statement();
    } else {
      ;
    }
{if ("" != null) return new Absyn.IfStmt(test, thenStmt, elseStmt);}
    throw new Error("Missing return statement in function");
}

// WhileStatement       ::=     "while" "(" Expression ")" Statement
  static final public Absyn.WhileStmt WhileStatement() throws ParseException {Absyn.Expr test;
    Absyn.Stmt body;
    jj_consume_token(17);
    jj_consume_token(38);
    test = Expression();
    jj_consume_token(39);
    body = Statement();
{if ("" != null) return new Absyn.WhileStmt(test, body);}
    throw new Error("Missing return statement in function");
}

// AssignStatement      ::=     AssignableExpression "=" Expression ";"
  static final public Absyn.AssignStmt AssignStatement() throws ParseException {Absyn.AssignableExpr target;
    Absyn.Expr value;
    target = AssignableExpression();
    jj_consume_token(27);
    value = Expression();
    jj_consume_token(42);
{if ("" != null) return new Absyn.AssignStmt(target, value);}
    throw new Error("Missing return statement in function");
}

// AssignableExpression ::=     Identifier
//                         |    Identifier "[" Expression "]"
//                         |    Identifier "." Identifier
//                         |    "this" "." Identifier
  static final public Absyn.AssignableExpr AssignableExpression() throws ParseException {Absyn.AssignableExpr e;
    Absyn.Expr index;
    Token name, field;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      name = jj_consume_token(ID);
e = new Absyn.IdentifierExpr(name.toString());
      break;
      }
    case 20:{
      jj_consume_token(20);
      jj_consume_token(35);
      field = jj_consume_token(ID);
e = new Absyn.FieldExpr(new Absyn.ThisExpr(), field.toString());
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 35:
      case 40:{
        ;
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 40:{
        jj_consume_token(40);
        index = Expression();
        jj_consume_token(41);
e = new Absyn.ArrayExpr(e, index);
        break;
        }
      case 35:{
        jj_consume_token(35);
        field = jj_consume_token(ID);
e = new Absyn.FieldExpr(e, field.toString());
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

// XinuCallStatement    ::=     "Xinu" "." Identifier "(" Arguments ")" ";"
  static final public Absyn.XinuCallStmt XinuCallStatement() throws ParseException {Token method;
    LinkedList<Absyn.Expr> args;
    jj_consume_token(47);
    jj_consume_token(35);
    method = jj_consume_token(ID);
    jj_consume_token(38);
    args = Arguments();
    jj_consume_token(39);
    jj_consume_token(42);
{if ("" != null) return new Absyn.XinuCallStmt(method.toString(), args);}
    throw new Error("Missing return statement in function");
}

// Arguments            ::=     ( Expression ( "," Expression )* )?
  static final public LinkedList<Absyn.Expr> Arguments() throws ParseException {Absyn.Expr e;
    LinkedList<Absyn.Expr> args = new LinkedList<Absyn.Expr>();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 31:
    case 34:
    case 38:
    case 47:
    case INT:
    case STRING:
    case ID:{
      e = Expression();
args.add(e);
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 43:{
          ;
          break;
          }
        default:
          jj_la1[18] = jj_gen;
          break label_9;
        }
        jj_consume_token(43);
        e = Expression();
args.add(e);
      }
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      ;
    }
{if ("" != null) return args;}
    throw new Error("Missing return statement in function");
}

// Expression           ::=     OrExpression
  static final public Absyn.Expr Expression() throws ParseException {Absyn.Expr e;
    e = OrExpression();
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

// OrExpression         ::=     AndExpression ( "||" AndExpression )*
  static final public Absyn.Expr OrExpression() throws ParseException {Absyn.Expr e1, e2;
    e1 = AndExpression();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 26:{
        ;
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        break label_10;
      }
      jj_consume_token(26);
      e2 = AndExpression();
e1 = new Absyn.OrExpr(e1, e2);
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

// AndExpression        ::=     EqualityExpression ( "&&" EqualityExpression )*
  static final public Absyn.Expr AndExpression() throws ParseException {Absyn.Expr e1, e2;
    e1 = EqualityExpression();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 25:{
        ;
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        break label_11;
      }
      jj_consume_token(25);
      e2 = EqualityExpression();
e1 = new Absyn.AndExpr(e1, e2);
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

// EqualityExpression   ::=     RelationalExpression
//                              ( ( "==" | "!=" ) RelationalExpression )*
  static final public Absyn.Expr EqualityExpression() throws ParseException {Absyn.Expr e1, e2;
    e1 = RelationalExpression();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 23:
      case 24:{
        ;
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 23:{
        jj_consume_token(23);
        e2 = RelationalExpression();
e1 = new Absyn.EqualExpr(e1, e2);
        break;
        }
      case 24:{
        jj_consume_token(24);
        e2 = RelationalExpression();
e1 = new Absyn.NotEqExpr(e1, e2);
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

// RelationalExpression ::=     AdditiveExpression
//                              ( ( "<" | ">" ) AdditiveExpression )*
  static final public Absyn.Expr RelationalExpression() throws ParseException {Absyn.Expr e1, e2;
    e1 = AdditiveExpression();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 28:
      case 29:{
        ;
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        break label_13;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 28:{
        jj_consume_token(28);
        e2 = AdditiveExpression();
e1 = new Absyn.LesserExpr(e1, e2);
        break;
        }
      case 29:{
        jj_consume_token(29);
        e2 = AdditiveExpression();
e1 = new Absyn.GreaterExpr(e1, e2);
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

// AdditiveExpression   ::=     MultiplicativeExpression
//                              ( ( "+" | "-" ) MultiplicativeExpression )*
  static final public Absyn.Expr AdditiveExpression() throws ParseException {Absyn.Expr e1, e2;
    e1 = MultiplicativeExpression();
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 30:
      case 31:{
        ;
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        break label_14;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 30:{
        jj_consume_token(30);
        e2 = MultiplicativeExpression();
e1 = new Absyn.AddExpr(e1, e2);
        break;
        }
      case 31:{
        jj_consume_token(31);
        e2 = MultiplicativeExpression();
e1 = new Absyn.SubExpr(e1, e2);
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

// MultiplicativeExpression ::= UnaryExpression
//                              ( ( "*" | "/" ) UnaryExpression )*
  static final public Absyn.Expr MultiplicativeExpression() throws ParseException {Absyn.Expr e1, e2;
    e1 = UnaryExpression();
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 32:
      case 33:{
        ;
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        break label_15;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 32:{
        jj_consume_token(32);
        e2 = UnaryExpression();
e1 = new Absyn.MulExpr(e1, e2);
        break;
        }
      case 33:{
        jj_consume_token(33);
        e2 = UnaryExpression();
e1 = new Absyn.DivExpr(e1, e2);
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

// UnaryExpression      ::=     "!" UnaryExpression
//                         |    "-" UnaryExpression
//                         |    PostfixExpression
  static final public Absyn.Expr UnaryExpression() throws ParseException {Absyn.Expr e;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 34:{
      jj_consume_token(34);
      e = UnaryExpression();
{if ("" != null) return new Absyn.NotExpr(e);}
      break;
      }
    case 31:{
      jj_consume_token(31);
      e = UnaryExpression();
{if ("" != null) return new Absyn.NegExpr(e);}
      break;
      }
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 38:
    case 47:
    case INT:
    case STRING:
    case ID:{
      e = PostfixExpression();
{if ("" != null) return e;}
      break;
      }
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// PostfixExpression    ::=     PrimaryExpression
//                              ( "[" Expression "]"
//                              | "." Identifier
//                              | "." Identifier "(" Arguments ")" )*
  static final public Absyn.Expr PostfixExpression() throws ParseException {Absyn.Expr e, index;
    Token name;
    LinkedList<Absyn.Expr> args;
    e = PrimaryExpression();
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 35:
      case 40:{
        ;
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        break label_16;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 40:{
        jj_consume_token(40);
        index = Expression();
        jj_consume_token(41);
e = new Absyn.ArrayExpr(e, index);
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        if (jj_2_7(2147483647)) {
          jj_consume_token(35);
          name = jj_consume_token(ID);
          jj_consume_token(38);
          args = Arguments();
          jj_consume_token(39);
e = new Absyn.CallExpr(e, name.toString(), args);
        } else {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 35:{
            jj_consume_token(35);
            name = jj_consume_token(ID);
e = new Absyn.FieldExpr(e, name.toString());
            break;
            }
          default:
            jj_la1[33] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    }
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

// PrimaryExpression    ::=     StringLiteral
//                         |    IntegerLiteral
//                         |    "true"
//                         |    "false"
//                         |    "this"
//                         |    "null"
//                         |    Identifier
//                         |    "(" Expression ")"
//                         |    NewExpression
//                         |    XinuCallExpression
  static final public Absyn.Expr PrimaryExpression() throws ParseException {Token t;
    Absyn.Expr e;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRING:{
      t = jj_consume_token(STRING);
{if ("" != null) return new Absyn.StringLiteral(t.toString());}
      break;
      }
    case INT:{
      t = jj_consume_token(INT);
{if ("" != null) return new Absyn.IntegerLiteral(Integer.parseInt(t.toString()));}
      break;
      }
    case 18:{
      jj_consume_token(18);
{if ("" != null) return new Absyn.TrueExpr();}
      break;
      }
    case 19:{
      jj_consume_token(19);
{if ("" != null) return new Absyn.FalseExpr();}
      break;
      }
    case 20:{
      jj_consume_token(20);
{if ("" != null) return new Absyn.ThisExpr();}
      break;
      }
    case 21:{
      jj_consume_token(21);
{if ("" != null) return new Absyn.NullExpr();}
      break;
      }
    case ID:{
      t = jj_consume_token(ID);
{if ("" != null) return new Absyn.IdentifierExpr(t.toString());}
      break;
      }
    case 38:{
      jj_consume_token(38);
      e = Expression();
      jj_consume_token(39);
{if ("" != null) return e;}
      break;
      }
    case 22:{
      e = NewExpression();
{if ("" != null) return e;}
      break;
      }
    case 47:{
      e = XinuCallExpression();
{if ("" != null) return e;}
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// NewExpression        ::=     "new" BaseType "(" ")"
//                         |    "new" BaseType "[" Expression "]" ( "[" "]" )*
  static final public Absyn.Expr NewExpression() throws ParseException {Absyn.Type type;
    Absyn.Expr size;
    LinkedList<Absyn.Expr> dimensions;
    jj_consume_token(22);
    type = BaseType();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 38:{
      jj_consume_token(38);
      jj_consume_token(39);
{if ("" != null) return new Absyn.NewObjectExpr(type);}
      break;
      }
    case 40:{
      jj_consume_token(40);
      size = Expression();
      jj_consume_token(41);
dimensions = new LinkedList<Absyn.Expr>();
              dimensions.add(size);
      label_17:
      while (true) {
        if (jj_2_8(2)) {
          ;
        } else {
          break label_17;
        }
        jj_consume_token(40);
        jj_consume_token(41);
dimensions.add(null);
      }
{if ("" != null) return new Absyn.NewArrayExpr(type, dimensions);}
      break;
      }
    default:
      jj_la1[35] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// XinuCallExpression   ::=     "Xinu" "." Identifier "(" Arguments ")"
  static final public Absyn.XinuCallExpr XinuCallExpression() throws ParseException {Token method;
    LinkedList<Absyn.Expr> args;
    jj_consume_token(47);
    jj_consume_token(35);
    method = jj_consume_token(ID);
    jj_consume_token(38);
    args = Arguments();
    jj_consume_token(39);
{if ("" != null) return new Absyn.XinuCallExpr(method.toString(), args);}
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_3R_PrimaryExpression_756_7_76()
 {
    if (jj_3R_NewExpression_772_5_81()) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_753_7_75()
 {
    if (jj_scan_token(38)) return true;
    if (jj_3R_Expression_560_5_29()) return true;
    if (jj_scan_token(39)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_750_7_74()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_Expression_560_5_29()
 {
    if (jj_3R_OrExpression_570_5_38()) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_747_7_73()
 {
    if (jj_scan_token(21)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_744_7_72()
 {
    if (jj_scan_token(20)) return true;
    return false;
  }

  static private boolean jj_3R_Arguments_546_13_87()
 {
    if (jj_scan_token(43)) return true;
    if (jj_3R_Expression_560_5_29()) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_3R_VarDeclaration_380_5_18()) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_741_7_71()
 {
    if (jj_scan_token(19)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_738_7_70()
 {
    if (jj_scan_token(18)) return true;
    return false;
  }

  static private boolean jj_3R_Arguments_542_9_86()
 {
    if (jj_3R_Expression_560_5_29()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Arguments_546_13_87()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_735_7_69()
 {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_732_7_66()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PrimaryExpression_732_7_68()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_735_7_69()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_738_7_70()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_741_7_71()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_744_7_72()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_747_7_73()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_750_7_74()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_753_7_75()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_756_7_76()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_759_7_77()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_732_7_68()
 {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  static private boolean jj_3R_Arguments_541_5_83()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Arguments_542_9_86()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_scan_token(6)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(9)) return true;
    if (jj_scan_token(46)) return true;
    return false;
  }

  static private boolean jj_3_7()
 {
    if (jj_scan_token(35)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(38)) return true;
    return false;
  }

  static private boolean jj_3R_XinuCallStatement_528_5_34()
 {
    if (jj_scan_token(47)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpression_709_11_80()
 {
    if (jj_scan_token(35)) return true;
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpression_704_11_79()
 {
    if (jj_scan_token(35)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(38)) return true;
    if (jj_3R_Arguments_541_5_83()) return true;
    if (jj_scan_token(39)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpression_701_11_67()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PostfixExpression_701_11_78()) {
    jj_scanpos = xsp;
    if (jj_3R_PostfixExpression_704_11_79()) {
    jj_scanpos = xsp;
    if (jj_3R_PostfixExpression_709_11_80()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_PostfixExpression_701_11_78()
 {
    if (jj_scan_token(40)) return true;
    if (jj_3R_Expression_560_5_29()) return true;
    if (jj_scan_token(41)) return true;
    return false;
  }

  static private boolean jj_3R_AssignableExpression_506_11_43()
 {
    if (jj_scan_token(20)) return true;
    return false;
  }

  static private boolean jj_3R_AssignableExpression_503_11_42()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpression_699_5_65()
 {
    if (jj_3R_PrimaryExpression_732_7_66()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_PostfixExpression_701_11_67()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_AssignableExpression_502_5_39()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_AssignableExpression_503_11_42()) {
    jj_scanpos = xsp;
    if (jj_3R_AssignableExpression_506_11_43()) return true;
    }
    return false;
  }

  static private boolean jj_3R_UnaryExpression_684_7_62()
 {
    if (jj_3R_PostfixExpression_699_5_65()) return true;
    return false;
  }

  static private boolean jj_3R_UnaryExpression_681_7_61()
 {
    if (jj_scan_token(31)) return true;
    if (jj_3R_UnaryExpression_678_7_56()) return true;
    return false;
  }

  static private boolean jj_3R_UnaryExpression_678_7_56()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_UnaryExpression_678_7_60()) {
    jj_scanpos = xsp;
    if (jj_3R_UnaryExpression_681_7_61()) {
    jj_scanpos = xsp;
    if (jj_3R_UnaryExpression_684_7_62()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_UnaryExpression_678_7_60()
 {
    if (jj_scan_token(34)) return true;
    if (jj_3R_UnaryExpression_678_7_56()) return true;
    return false;
  }

  static private boolean jj_3R_AssignStatement_485_5_33()
 {
    if (jj_3R_AssignableExpression_502_5_39()) return true;
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpression_663_11_64()
 {
    if (jj_scan_token(33)) return true;
    if (jj_3R_UnaryExpression_678_7_56()) return true;
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpression_660_11_57()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_MultiplicativeExpression_660_11_63()) {
    jj_scanpos = xsp;
    if (jj_3R_MultiplicativeExpression_663_11_64()) return true;
    }
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpression_660_11_63()
 {
    if (jj_scan_token(32)) return true;
    if (jj_3R_UnaryExpression_678_7_56()) return true;
    return false;
  }

  static private boolean jj_3R_WhileStatement_472_5_32()
 {
    if (jj_scan_token(17)) return true;
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpression_658_5_52()
 {
    if (jj_3R_UnaryExpression_678_7_56()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MultiplicativeExpression_660_11_57()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_scan_token(16)) return true;
    if (jj_3R_Statement_426_7_19()) return true;
    return false;
  }

  static private boolean jj_3R_AdditiveExpression_644_11_59()
 {
    if (jj_scan_token(31)) return true;
    if (jj_3R_MultiplicativeExpression_658_5_52()) return true;
    return false;
  }

  static private boolean jj_3R_AdditiveExpression_641_11_53()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_AdditiveExpression_641_11_58()) {
    jj_scanpos = xsp;
    if (jj_3R_AdditiveExpression_644_11_59()) return true;
    }
    return false;
  }

  static private boolean jj_3R_AdditiveExpression_641_11_58()
 {
    if (jj_scan_token(30)) return true;
    if (jj_3R_MultiplicativeExpression_658_5_52()) return true;
    return false;
  }

  static private boolean jj_3R_IfStatement_455_5_31()
 {
    if (jj_scan_token(15)) return true;
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_scan_token(7)) return true;
    return false;
  }

  static private boolean jj_3R_AdditiveExpression_639_5_48()
 {
    if (jj_3R_MultiplicativeExpression_658_5_52()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AdditiveExpression_641_11_53()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_scan_token(7)) return true;
    if (jj_scan_token(12)) return true;
    return false;
  }

  static private boolean jj_3R_RelationalExpression_625_11_55()
 {
    if (jj_scan_token(29)) return true;
    if (jj_3R_AdditiveExpression_639_5_48()) return true;
    return false;
  }

  static private boolean jj_3R_BlockStatement_439_5_30()
 {
    if (jj_scan_token(36)) return true;
    return false;
  }

  static private boolean jj_3R_RelationalExpression_622_11_49()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_RelationalExpression_622_11_54()) {
    jj_scanpos = xsp;
    if (jj_3R_RelationalExpression_625_11_55()) return true;
    }
    return false;
  }

  static private boolean jj_3R_RelationalExpression_622_11_54()
 {
    if (jj_scan_token(28)) return true;
    if (jj_3R_AdditiveExpression_639_5_48()) return true;
    return false;
  }

  static private boolean jj_3R_Statement_430_7_26()
 {
    if (jj_3R_XinuCallStatement_528_5_34()) return true;
    return false;
  }

  static private boolean jj_3R_Statement_429_7_25()
 {
    if (jj_3R_AssignStatement_485_5_33()) return true;
    return false;
  }

  static private boolean jj_3R_Statement_428_7_24()
 {
    if (jj_3R_WhileStatement_472_5_32()) return true;
    return false;
  }

  static private boolean jj_3R_Statement_427_7_23()
 {
    if (jj_3R_IfStatement_455_5_31()) return true;
    return false;
  }

  static private boolean jj_3R_RelationalExpression_620_5_46()
 {
    if (jj_3R_AdditiveExpression_639_5_48()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_RelationalExpression_622_11_49()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Statement_426_7_19()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Statement_426_7_22()) {
    jj_scanpos = xsp;
    if (jj_3R_Statement_427_7_23()) {
    jj_scanpos = xsp;
    if (jj_3R_Statement_428_7_24()) {
    jj_scanpos = xsp;
    if (jj_3R_Statement_429_7_25()) {
    jj_scanpos = xsp;
    if (jj_3R_Statement_430_7_26()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_Statement_426_7_22()
 {
    if (jj_3R_BlockStatement_439_5_30()) return true;
    return false;
  }

  static private boolean jj_3R_EqualityExpression_606_11_51()
 {
    if (jj_scan_token(24)) return true;
    if (jj_3R_RelationalExpression_620_5_46()) return true;
    return false;
  }

  static private boolean jj_3R_XinuCallExpression_800_5_82()
 {
    if (jj_scan_token(47)) return true;
    if (jj_scan_token(35)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(38)) return true;
    if (jj_3R_Arguments_541_5_83()) return true;
    if (jj_scan_token(39)) return true;
    return false;
  }

  static private boolean jj_3R_EqualityExpression_603_11_47()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_EqualityExpression_603_11_50()) {
    jj_scanpos = xsp;
    if (jj_3R_EqualityExpression_606_11_51()) return true;
    }
    return false;
  }

  static private boolean jj_3R_EqualityExpression_603_11_50()
 {
    if (jj_scan_token(23)) return true;
    if (jj_3R_RelationalExpression_620_5_46()) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_412_7_37()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_scan_token(7)) return true;
    return false;
  }

  static private boolean jj_3_8()
 {
    if (jj_scan_token(40)) return true;
    if (jj_scan_token(41)) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_409_7_36()
 {
    if (jj_scan_token(14)) return true;
    return false;
  }

  static private boolean jj_3R_EqualityExpression_601_5_44()
 {
    if (jj_3R_RelationalExpression_620_5_46()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_EqualityExpression_603_11_47()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_BaseType_406_7_35()
 {
    if (jj_scan_token(13)) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_406_7_27()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_BaseType_406_7_35()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseType_409_7_36()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseType_412_7_37()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_NewExpression_777_11_85()
 {
    if (jj_scan_token(40)) return true;
    if (jj_3R_Expression_560_5_29()) return true;
    if (jj_scan_token(41)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_8()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_AndExpression_587_9_45()
 {
    if (jj_scan_token(25)) return true;
    if (jj_3R_EqualityExpression_601_5_44()) return true;
    return false;
  }

  static private boolean jj_3R_NewExpression_774_11_84()
 {
    if (jj_scan_token(38)) return true;
    if (jj_scan_token(39)) return true;
    return false;
  }

  static private boolean jj_3R_Type_395_7_28()
 {
    if (jj_scan_token(40)) return true;
    if (jj_scan_token(41)) return true;
    return false;
  }

  static private boolean jj_3R_Type_394_5_20()
 {
    if (jj_3R_BaseType_406_7_27()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Type_395_7_28()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_AndExpression_585_5_40()
 {
    if (jj_3R_EqualityExpression_601_5_44()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AndExpression_587_9_45()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_NewExpression_772_5_81()
 {
    if (jj_scan_token(22)) return true;
    if (jj_3R_BaseType_406_7_27()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_NewExpression_774_11_84()) {
    jj_scanpos = xsp;
    if (jj_3R_NewExpression_777_11_85()) return true;
    }
    return false;
  }

  static private boolean jj_3R_OrExpression_572_9_41()
 {
    if (jj_scan_token(26)) return true;
    if (jj_3R_AndExpression_585_5_40()) return true;
    return false;
  }

  static private boolean jj_3R_VarDeclaration_382_7_21()
 {
    if (jj_scan_token(27)) return true;
    if (jj_3R_Expression_560_5_29()) return true;
    return false;
  }

  static private boolean jj_3R_VarDeclaration_380_5_18()
 {
    if (jj_3R_Type_394_5_20()) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_VarDeclaration_382_7_21()) jj_scanpos = xsp;
    if (jj_scan_token(42)) return true;
    return false;
  }

  static private boolean jj_3R_OrExpression_570_5_38()
 {
    if (jj_3R_AndExpression_585_5_40()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_OrExpression_572_9_41()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_759_7_77()
 {
    if (jj_3R_XinuCallExpression_800_5_82()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MiniJavaParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[36];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x40,0x40,0x200,0x6080,0x6000,0x6080,0x6000,0x800,0x0,0x6000,0x128000,0x8000000,0x0,0x6000,0x128000,0x100000,0x0,0x0,0x0,0x807c0000,0x4000000,0x2000000,0x1800000,0x1800000,0x30000000,0x30000000,0xc0000000,0xc0000000,0x0,0x0,0x807c0000,0x0,0x0,0x0,0x7c0000,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x0,0x40000,0x40000,0x40000,0x40000,0x0,0x800,0x40000,0x48010,0x0,0x100,0x40000,0x48010,0x40000,0x108,0x108,0x800,0x78044,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3,0x3,0x78044,0x108,0x100,0x8,0x78040,0x140,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[8];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniJavaParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniJavaParser(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniJavaParser(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniJavaParser(MiniJavaParserTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniJavaParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[55];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 36; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 55; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 8; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

                               }
